import type { CollectionConfig } from 'payload'

export const Listings: CollectionConfig = {
  slug: 'listings',
  admin: { defaultColumns: ['listingId', 'status', 'city', 'listPrice', 'updatedAt'] },
  access: { read: () => true },
  fields: [
    { name: 'listingId', type: 'text', unique: true, required: true },
    { name: 'addressLine1', type: 'text' },
    { name: 'city', type: 'text' },
    { name: 'state', type: 'text' },
    { name: 'postalCode', type: 'text' },
    {
      name: 'location',
      type: 'point',
      label: 'Location',
    },
    { name: 'propertyType', type: 'text' },
    { name: 'propertySubType', type: 'text' },
    { name: 'bedrooms', type: 'number' },
    { name: 'bathrooms', type: 'number' },
    { name: 'halfBaths', type: 'number' },
    { name: 'squareFootage', type: 'number' },
    { name: 'yearBuilt', type: 'number' },
    { name: 'listPrice', type: 'number' },
    { name: 'originalListPrice', type: 'number' },
    { name: 'pricePerSquareFoot', type: 'number' },
    { name: 'buildingName', type: 'text' },
    { name: 'unitNumber', type: 'text' },
    { name: 'floor', type: 'number' },
    { name: 'totalFloorsInBuilding', type: 'number' },
    { name: 'unitsInBuilding', type: 'number' },
    { name: 'hoaFee', type: 'number' },
    { name: 'hoaFrequency', type: 'text' },
    { name: 'listingDate', type: 'date' },
    { name: 'daysOnMarket', type: 'number' },
    {
      name: 'listingAgent',
      type: 'group',
      fields: [
        { name: 'id', type: 'text' },
        { name: 'name', type: 'text' },
        { name: 'email', type: 'email' },
        { name: 'phone', type: 'text' },
      ],
    },
    { name: 'photos', type: 'array', fields: [{ name: 'url', type: 'text' }] },
    { name: 'features', type: 'array', fields: [{ name: 'value', type: 'text' }] },
    { name: 'appliances', type: 'array', fields: [{ name: 'value', type: 'text' }] },
    { name: 'amenities', type: 'array', fields: [{ name: 'value', type: 'text' }] },
    { name: 'status', type: 'text' },
    { name: 'lastUpdated', type: 'date' },
    { name: 'source', type: 'text' },
  ],
  indexes: [
    { fields: ['listingId'], unique: true },
    { fields: ['status'] },
    { fields: ['city'] },
    { fields: ['listPrice'] },
    { fields: ['updatedAt'] },
  ],
}

export default Listings
